---
- name: Set up Nginx
  hosts: all
  become: true
  tasks:

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Copy index.html to Nginx web root
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.nginx-debian.html
        owner: root
        group: root
        mode: '0644'

    - name: Restart Nginx to apply changes
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: Install curl
      ansible.builtin.apt:
        name: curl
        state: present

    - name: Check Nginx response
      ansible.builtin.command:
        cmd: curl localhost
