---
# tasks file for ec2-instance
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "my-ec2-instance"
    key_name: "Mahesh"
    instance_type: "{{ type }}"
    security_group: default
    region: us-east-1
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    network_interfaces:
      - assign_public_ip: true
    image_id: ami-020cba7c55df1f615
    tags:
      Environment: Test
